"""PPTX export — convert HTML slide presentations to PowerPoint (.pptx) files.

Handles the output of the ppt-animation skill (and similar HTML-based slide
generators). Extracts slide content from HTML, creates a PPTX with one slide
per HTML section.
"""
from __future__ import annotations

import re
import uuid
import logging
from pathlib import Path
from typing import Optional

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

logger = logging.getLogger("ppt_export")

# Common slide container selectors / patterns in skill-generated HTML
_SLIDE_RE = re.compile(
    r'<div[^>]*class="[^"]*slide[^"]*"[^>]*>.*?</div>\s*(?=<div[^>]*class="[^"]*slide[^"]*"|</body>|$)',
    re.DOTALL | re.IGNORECASE,
)
_SLIDE_TAG_RE = re.compile(
    r'<(?:section|article)[^>]*class="[^"]*(?:slide|page)[^"]*"[^>]*>.*?</(?:section|article)>',
    re.DOTALL | re.IGNORECASE,
)
_TITLE_RE = re.compile(r'<h([12])[^>]*>(.*?)</h\1>', re.DOTALL | re.IGNORECASE)
_TAG_STRIP_RE = re.compile(r'<[^>]+>')
_ENTITY_RE = re.compile(r'&[a-z]+;|&#\d+;')
_WHITESPACE_RE = re.compile(r'\s+')

# HTML entities
_ENTITIES = {
    "&amp;": "&", "&lt;": "<", "&gt;": ">", "&quot;": '"',
    "&apos;": "'", "&nbsp;": " ", "&#39;": "'",
}


def _decode_entities(text: str) -> str:
    """Decode common HTML entities."""
    for entity, char in _ENTITIES.items():
        text = text.replace(entity, char)
    return _ENTITY_RE.sub(" ", text)


def _strip_tags(text: str) -> str:
    """Strip HTML tags and decode entities, returning clean text."""
    text = _decode_entities(text)
    text = _TAG_STRIP_RE.sub(" ", text)
    return _WHITESPACE_RE.sub(" ", text).strip()


def _extract_slides_from_html(html: str) -> list[dict]:
    """Parse HTML and extract slide sections.

    Returns a list of ``{title, content, index}`` dicts.
    Handles ``<div class="slide">`` and ``<section class="slide">`` patterns.
    """
    # Try div.slide first
    slides_raw = _SLIDE_RE.findall(html)
    if not slides_raw:
        slides_raw = _SLIDE_TAG_RE.findall(html)

    # If no class-based slides found, try splitting by h1 tags
    if not slides_raw:
        parts = re.split(r'(<h1[^>]*>.*?</h1>)', html, flags=re.DOTALL | re.IGNORECASE)
        slides_raw = []
        current = ""
        for part in parts:
            if re.match(r'<h1[^>]*>', part, re.IGNORECASE):
                if current.strip():
                    slides_raw.append(current)
                current = part
            else:
                current += part
        if current.strip():
            slides_raw.append(current)

    slides: list[dict] = []
    for i, raw in enumerate(slides_raw):
        # Extract title
        title = ""
        title_match = _TITLE_RE.search(raw)
        if title_match:
            title = _strip_tags(title_match.group(0))

        # Extract text content (remove script/style blocks first)
        clean = re.sub(r'<(?:script|style)[^>]*>.*?</(?:script|style)>', '', raw, flags=re.DOTALL | re.IGNORECASE)
        body_text = _strip_tags(clean)

        # Trim body text (remove title from beginning)
        if title and body_text.startswith(title):
            body_text = body_text[len(title):].strip()

        slides.append({
            "title": title or f"Slide {i + 1}",
            "content": body_text[:2000],  # Limit content length per slide
            "index": i,
        })

    return slides


def html_to_pptx(
    html_content: str,
    output_path: Optional[str] = None,
    title: str = "Presentation",
) -> str:
    """Convert an HTML slide presentation to a PPTX file.

    Parameters
    ----------
    html_content : str
        The complete HTML content (as generated by ppt-animation skill).
    output_path : str, optional
        Where to write the PPTX. Defaults to a temp path under outputs/.
    title : str
        Presentation title (used for the first slide if no title found).

    Returns
    -------
    str
        Absolute path to the generated PPTX file.
    """
    if output_path is None:
        file_id = uuid.uuid4().hex[:12]
        output_path = str(Path(__file__).parent.parent.parent / "outputs" / f"export_{file_id}.pptx")

    slides = _extract_slides_from_html(html_content)

    if not slides:
        # Fallback: create a single slide from the HTML body text
        body = re.sub(r'<(?:script|style|head)[^>]*>.*?</(?:script|style|head)>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
        body_text = _strip_tags(body)
        slides = [{"title": title, "content": body_text[:3000], "index": 0}]

    prs = Presentation()
    prs.slide_width = Inches(13.333)  # 16:9 widescreen
    prs.slide_height = Inches(7.5)

    # ── Title slide ──
    if len(slides) > 1:
        title_slide_layout = prs.slide_layouts[0]  # Title Slide layout
        slide_obj = prs.slides.add_slide(title_slide_layout)
        if slide_obj.shapes.title:
            slide_obj.shapes.title.text = title
        if slide_obj.placeholders and len(slide_obj.placeholders) > 1:
            slide_obj.placeholders[1].text = f"共 {len(slides)} 页"

    # ── Content slides ──
    for s in slides:
        # Use blank layout for custom formatting
        blank_layout = prs.slide_layouts[6]  # Blank
        slide_obj = prs.slides.add_slide(blank_layout)

        # Title box
        left = Inches(0.8)
        top = Inches(0.4)
        width = Inches(11.7)
        height = Inches(1.0)
        title_box = slide_obj.shapes.add_textbox(left, top, width, height)
        title_frame = title_box.text_frame
        title_frame.word_wrap = True
        p = title_frame.paragraphs[0]
        p.text = s["title"]
        p.font.size = Pt(32)
        p.font.bold = True
        p.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)
        p.alignment = PP_ALIGN.LEFT

        # Content box
        content_top = Inches(1.6)
        content_height = Inches(5.5)
        content_box = slide_obj.shapes.add_textbox(left, content_top, width, content_height)
        content_frame = content_box.text_frame
        content_frame.word_wrap = True

        # Split content into paragraphs
        paragraphs = [p for p in s["content"].split("\n") if p.strip()]
        if not paragraphs:
            paragraphs = [s["content"]]

        for j, para_text in enumerate(paragraphs[:15]):  # Max 15 paragraphs per slide
            if j == 0:
                p = content_frame.paragraphs[0]
            else:
                p = content_frame.add_paragraph()
            p.text = para_text[:500]
            p.font.size = Pt(18)
            p.font.color.rgb = RGBColor(0x33, 0x33, 0x44)
            p.space_after = Pt(8)
            p.alignment = PP_ALIGN.LEFT

    prs.save(output_path)
    logger.info(f"PPTX exported: {output_path} ({len(slides)} slides)")
    return output_path


def export_skill_to_pptx(
    html_content: str,
    skill_name: str = "ppt-animation",
    title: str = "",
) -> dict:
    """Export skill HTML output as PPTX and return file info for API response.

    Returns ``{"file_url": str, "file_path": str, "slides": int, "title": str}``.
    """
    file_id = uuid.uuid4().hex[:12]
    output_path = str(
        Path(__file__).parent.parent.parent / "outputs" / f"{skill_name}_{file_id}.pptx"
    )

    # Extract title from HTML if not provided
    if not title:
        title_match = re.search(r'<title>(.*?)</title>', html_content, re.IGNORECASE)
        if title_match:
            title = title_match.group(1).strip()
    if not title:
        title = f"{skill_name} 演示文稿"

    file_path = html_to_pptx(html_content, output_path=output_path, title=title)

    slides = _extract_slides_from_html(html_content)

    return {
        "file_url": f"/outputs/{Path(file_path).name}",
        "file_path": file_path,
        "slides": len(slides),
        "title": title,
    }
